---
abstract: 'Generate a trigger-based SQL tree implementation'
author:
  - 'Mark Lawrence <nomad@null.net>'
build_requires:
  DBD::SQLite: 0
  DBI: 0
  ExtUtils::MakeMaker: 6.42
  Test::Database: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: Gpl_3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Tree
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Getopt::Long::Descriptive: 0
resources:
  repository: git://github.com/mlawren/sql-tree.git
version: 0.01
